/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oDj0ON3wYM9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Room() {
  return (
    <div className="flex flex-col h-screen bg-background">

      <main className="flex-1 p-8 flex flex-col items-center justify-center gap-8">
        <div className="grid grid-cols-7 gap-4">
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            1
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            2
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            3
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            5
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            8
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            13
          </Button>
          <Button variant="ghost" className="w-12 h-12 rounded-full text-2xl font-bold">
            21
          </Button>
        </div>
        <Button className="px-6 py-3 rounded-md text-lg font-medium">Reveal Votes</Button>
        <div className="bg-card p-6 rounded-md w-full max-w-md">
          <h2 className="text-lg font-bold mb-4">Votes</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="flex flex-col items-center">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="John Doe" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium mt-2">John Doe</div>
              <div className="text-2xl font-bold text-primary">5</div>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Jane Smith" />
                <AvatarFallback>JS</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium mt-2">Jane Smith</div>
              <div className="text-2xl font-bold text-primary">8</div>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Bob Johnson" />
                <AvatarFallback>BJ</AvatarFallback>
              </Avatar>
              <div className="text-sm font-medium mt-2">Bob Johnson</div>
              <div className="text-2xl font-bold text-primary">3</div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
